#!/bin/env bash

# Define the target URL where /redirect_me should be redirected
#Install nginx web server
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }" > /etc/nginx/sites-available/default

# Test the NGINX configuration for syntax errors
nginx -t
service nginx start
