#!/usr/bin/env bash
#Types of network
What type of network a computer in local is connected to?

LAN (Local Area Network)
What type of network could connect an office in one building to another office in a building a few streets away?

WAN (Wide Area Network)
What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?

Internet
