#!/usr/bin/env bash
#UDP and TCP
1. **Which statement is correct for the TCP box:**
   - It is a protocol that is transferring data in a slow way but surely.

2. **Which statement is correct for the UDP box:**
   - It is a protocol that is transferring data in a fast way and might lose data along the process.

3. **Which statement is correct for the TCP worker:**
   - May I increase the rate at which I am sending you boxes?
